version: 3;

services:
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123012
      MYSQL_DATABASE: gin-chat
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
